server:
  port: 8080
spring:
  application:
    name: system
  config:
    import:
      - application-web.yml
      - application-log.yml
      - application-datasource.yml
      - application-mybatisPlus.yml